@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFhN2RlNGVkNGQ2NGY3MzIxMmNlNTUiLCJ1c2VybmFtZSI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzI4OTM5NDcsImV4cCI6MTc3Mjg5NDg0N30.ZgpYJ9ro91CF4gbcJ_x6iho847PZP5o4kIA53IJWK5E
GET http://localhost:3000/api/tasks
Authorization: Bearer {{token}}