@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlYWI0ZjE2YzU4MGUyZmI3MGQ2MDEiLCJ1c2VybmFtZSI6ImFiYzEyMyIsImlhdCI6MTc3MzA1NDkwNCwiZXhwIjoxNzczMDU1ODA0fQ.tDRkrboqjj-g3NSVC1BalALB3eOYjItYKITK9_Mq8ec
GET http://localhost:3000/api/tasks
Authorization: Bearer {{token}}