name: DevSecOps Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Dependency Audit
        run: npm audit --audit-level=high

      - name: Build Docker Image
        run: docker build -t secure-task-api .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-task-api
